"""add users updated_at

Revision ID: 7c3c43e81635
Revises: a97b8bd55c79
Create Date: 2026-02-02 17:11:44.748596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3c43e81635'
down_revision: Union[str, Sequence[str], None] = 'a97b8bd55c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('low', 'medium', 'high', 'critical', name='ticket_priority'),
               existing_nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('open', 'assigned', 'in_progress', 'resolved', 'closed', name='ticket_status'),
               existing_nullable=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.alter_column('tickets', 'status',
               existing_type=sa.Enum('open', 'assigned', 'in_progress', 'resolved', 'closed', name='ticket_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', name='ticket_priority'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('ticket_comments', 'updated_at')
    # ### end Alembic commands ###
